# Generated by Django 2.2.12 on 2021-12-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapes',
            name='shapes_choice',
            field=models.CharField(blank=True, choices=[('Square', 'Square'), ('Rectangle', 'Rectangle'), ('Triangle', 'Triangle')], max_length=30, null=True),
        ),
    ]
