# Generated by Django 2.2.12 on 2021-12-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0002_shapes_shapes_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapes',
            name='shapes_choice',
            field=models.CharField(blank=True, choices=[('square', 'Square'), ('rectangle', 'Rectangle'), ('triangle', 'Triangle')], max_length=30, null=True),
        ),
    ]
