# Generated by Django 2.2.12 on 2021-12-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0004_shapescomputation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShapesComputation',
        ),
        migrations.AddField(
            model_name='shapes',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
