# Generated by Django 2.2.12 on 2021-12-06 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0005_auto_20211205_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shapes',
            name='length',
        ),
    ]
