# Generated by Django 2.2.12 on 2021-12-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0006_remove_shapes_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapes',
            name='side',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
