# Generated by Django 2.2.12 on 2021-12-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0007_shapes_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapes',
            name='shapes_choice',
            field=models.CharField(blank=True, choices=[('square', 'Square'), ('triangle', 'Triangle')], max_length=30, null=True),
        ),
    ]
